### ISSUE TITLE
Error on Data Save ALM 184

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#692]
Browser: Chrome, IE, 
1. Go to: https://etools-staging.unicef.org/dash/
2. Select the "Partners" link - do not use the app selector.

result: 
![image](https://user-images.githubusercontent.com/26120371/30130413-03dcdab6-9317-11e7-9616-fc7d04b9ba7d.png)

**Comment by mpawlowski85** [comment]
Data from the console: 
Request URL:https://etools-staging.unicef.org/api/v2/partners/list/
Request Method:GET
Status Code:404 Not Found
Remote Address:23.97.169.141:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Content-Type:text/html; charset=utf-8
Date:Wed, 06 Sep 2017 19:12:37 GMT
Server:gunicorn/19.6.0
Transfer-Encoding:chunked
Vary:Cookie
X-Frame-Options:SAMEORIGIN
Request Headers
view source
accept:application/json
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.8
Connection:keep-alive
Cookie:__qca=P0-627379514-1487347178646; mousestats_vi=93c62f2468b7e5927619; __uvt=; CorexLanguageUNI=English; __utma=51236845.285388626.1487347183.1500911943.1503413128.36; __utmz=51236845.1499885372.33.8.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __unam=1c83e6d-15a8ba73076-13dec3e4-33; PD-ID=xrLZWA5Hkukps2prxm70wQOUcDG3zfmy/7M2XGsnhKXhWQ486E09Rmof/fQgNZHDc9qvYyyA3WdsBNuHL79fNATToz5DtBIGNhafl1guFbpCz56hr5PgMjUrb87HyHNrxFUCh5kTdrk4koJxmDogGZnbGkAKaJJQ2UfXLvNZWNUYsFk+x2bZAI6kCGm6tHXgU13nxq2+0b8Jox1Yt2KbAwwCPvid7pFWscbuBdyPaDSyjOl8F2jKjkLitINNoq3EjuZx+QTRN4KstnWRjceBQ8LNXjMSSmFsjQDWHesgSftBNzdAvVgp/6Wa/aHEKoVrqHZQBxZftEhdSveZmKO4UDnUJQ6nRLBnbFcUi7wyHEMKsHPFIjksmVCjI/XOKFdVsoxfkK58UJ6EavP8l9OKZQk22CZCmLXtgBMcSmNWQz1JtXCa41RmIXf0yeLFv3GBIHX1DiVEWPs=; _ga=GA1.2.487710960.1487021577; _gid=GA1.2.1046120103.1504621708; csrftoken=hcwOHBARrhtgtP9PK7NNXRobPR3dQ28s; sessionid=p8j93fs67ps2mxcofp5c9pw0v34hgjow; uvts=5iNHtmYm11Z4Fm0F
Host:etools-staging.unicef.org
Referer:https://etools-staging.unicef.org/pmp/partners/list/
User-Agent:Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by adi130987** [comment]
There is no request to `partners/list` in PMP, except partners-list.html vulcanized page request. We'll check this.

**Comment by marko911** [comment]
@mpawlowski85 this is fixed, will be in next staging push.

**Comment by mpawlowski85** [comment]
testing failed @marko911 @adi130987 - I am still getting the same result

**Comment by marko911** [comment]
@mpawlowski85 my mistake, I fixed it for the ctrl+click last week. Now it is fixed for all clicks. Will be included in this week's staging push. Apologies .

**Comment by marko911** [comment]
Fixed. In staging right now.

**Comment by mpawlowski85** [comment]
passed in staging
